//@version=6
strategy(
    "macro GC",
    overlay = true,
    max_bars_back = 2000,
    calc_on_every_tick = true,

    process_orders_on_close = true,
    initial_capital = 50000, // qty 1 -> needs to be greater than close of first bar * 10
    default_qty_type = strategy.fixed,
    default_qty_value = 1,
    commission_type = strategy.commission.cash_per_contract,
    commission_value = 1.35
)

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// CONSTANTS
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ZN_STRUCTURE_LOOKBACK = 4
E6_STRUCTURE_LOOKBACK = 7
GC_STRUCTURE_LOOKBACK = 5

GC_EARLY_ALIGNMENT_MIN_BARS  = 2 // wait for stability
GC_EARLY_ALIGNMENT_MAX_BARS = 11 // ensure move is early
GC_TAKE_PROFIT_POINTS = 2000

// DATA
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

ZN_SYMBOL = "CBOT:ZN1!"
E6_SYMBOL = "CME:6E1!"
GC_SYMBOL = "COMEX:GC1!"

ticker = ticker.standard(syminfo.tickerid)
isZN = str.contains(ticker, "ZN1!")
isE6 = str.contains(ticker, "6E1!")
isGC = str.contains(syminfo.tickerid, "MGC1!")
// isMGC = str.contains(syminfo.tickerid, "MGC1!")

var isZNupTrend = false
var isZNdownTrend = false
var isE6upTrend = false
var isE6downTrend = false
var gcSupportiveBars = 0
var gcHostileBars = 0
varip isBarStable = false
var isLongTradeActive = false
var isShortTradeActive = false
var entryPrice = close
var exitPrice = close
var profit = close

// SESSION CONTROL
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// asia: 1810-0200
// london: 0300-1130
// TRANSITION: 0400-0900 end of london, pre-US
// us: 0930-1600

// session windows (entry allowed)
inSessionTimes = "1815-0859,0915-1659" // isMGC ? "1815-0859" : "1800-1700"
isInSession = not na(time(timeframe.period, inSessionTimes, "America/New_York"))

// session closing (exit)
sessionClosingTime = "1659-1700"
isSessionClosing = not na(time(timeframe.period, sessionClosingTime, "America/New_York"))

// ZN
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

znOpen = request.security(ZN_SYMBOL, timeframe.period, open)
znVwap = request.security(ZN_SYMBOL, timeframe.period, ta.vwap(hlc3))

znBullishBreak = request.security(
     ZN_SYMBOL,
     timeframe.period,
     high > ta.highest(high[1], ZN_STRUCTURE_LOOKBACK))

znBearishBreak = request.security(
     ZN_SYMBOL,
     timeframe.period,
     ta.lowest(low[1], ZN_STRUCTURE_LOOKBACK) > low)

if znBullishBreak
    isZNupTrend := true
    isZNdownTrend := false

if znBearishBreak
    isZNupTrend := false
    isZNdownTrend := true

znAbove = znOpen > znVwap
znBelow = znVwap > znOpen

isZNsupportive =
     isZNupTrend
     and znAbove

isZNhostile =
     isZNdownTrend
     and znBelow

isZNneutral =
     not isZNsupportive
     and not isZNhostile

// 6E
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

e6Open = request.security(E6_SYMBOL, timeframe.period, open)
e6Vwap = request.security(E6_SYMBOL, timeframe.period, ta.vwap(hlc3))

e6BullishBreak = request.security(
     E6_SYMBOL,
     timeframe.period,
     high > ta.highest(high[1], E6_STRUCTURE_LOOKBACK))

e6BearishBreak = request.security(
     E6_SYMBOL,
     timeframe.period,
     ta.lowest(low[1], E6_STRUCTURE_LOOKBACK) > low)

if e6BullishBreak
    isE6upTrend := true
    isE6downTrend := false

if e6BearishBreak
    isE6upTrend := false
    isE6downTrend := true

e6Above = e6Open > e6Vwap
e6Below = e6Vwap > e6Open

isE6supportive =
     isE6upTrend
     and e6Above

isE6hostile =
     isE6downTrend
     and e6Below

isE6neutral =
     not isE6supportive
     and not isE6hostile

// MACRO REGIME
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

isMacroSupportive = isZNsupportive and isE6supportive
isMacroHostile = isZNhostile and isE6hostile
isMacroNeutral = not isMacroSupportive and not isMacroHostile

isLongMacroBroken = not isZNsupportive or not isE6supportive
isShortMacroBroken = not isZNhostile or not isE6hostile

// GC LOGIC
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

gcOpen = open
gcVwap = ta.vwap(hlc3)

gcBullishBreak =
     high > ta.highest(high[1], GC_STRUCTURE_LOOKBACK)

gcBearishBreak =
     ta.lowest(low[1], GC_STRUCTURE_LOOKBACK) > low

var bool isGCupTrend = false
var bool isGCdownTrend = false

if gcBullishBreak
    isGCupTrend := true
    isGCdownTrend := false

if gcBearishBreak
    isGCupTrend := false
    isGCdownTrend := true

gcAbove = gcOpen > gcVwap
gcBelow = gcVwap > gcOpen

isGCsupportive =
     // isGCupTrend
     // and
     gcAbove

isGChostile =
     // isGCdownTrend
     // and
     gcBelow

isGCneutral =
     not isGCsupportive
     and not isGChostile

// count trend bars
gcSupportiveBars := isGCsupportive ? gcSupportiveBars[1] + 1 : 0
gcHostileBars := isGChostile ? gcHostileBars[1] + 1 : 0

// early in new, stable trend
isGCsupportiveEarly =
     isGCsupportive
     and gcSupportiveBars > GC_EARLY_ALIGNMENT_MIN_BARS
     and GC_EARLY_ALIGNMENT_MAX_BARS >= gcSupportiveBars
isGChostileEarly =
     isGChostile
     and gcHostileBars > GC_EARLY_ALIGNMENT_MIN_BARS
     and GC_EARLY_ALIGNMENT_MAX_BARS >= gcHostileBars

// GC TRADE
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// calc_on_every_tick has ridiculous problem of pulling previous bar values into this bar just for the very first tick
// creates ghost signals that are not accurate, bar is stable on second tick and later
// additional related problem: first tick arrives at different time when assets pulled from security()
// znTime = request.security(ZN_SYMBOL, timeframe.period, time)
// e6Time = request.security(E6_SYMBOL, timeframe.period, time)
isBarStable := true
     // not barstate.isrealtime
     // or (
     //      not barstate.isnew
     //      and time == znTime
     //      and time == e6Time
     // )

// entry
isLongEntry =
     isBarStable
     and isInSession
     and not isLongTradeActive
     and not isShortTradeActive
     // and open > gcVwap
     and isMacroSupportive
     and isGCsupportiveEarly

isShortEntry =
     isBarStable
     and isInSession
     and not isLongTradeActive
     and not isShortTradeActive
     // and gcVwap > open
     and isMacroHostile
     and isGChostileEarly

var takeProfit = close

if isLongEntry
    isLongTradeActive := true
    isShortTradeActive := false
    entryPrice := close
    takeProfit := entryPrice + GC_TAKE_PROFIT_POINTS

if isShortEntry
    isLongTradeActive := false
    isShortTradeActive := true
    entryPrice := close
    takeProfit := entryPrice - GC_TAKE_PROFIT_POINTS

// exit
isLongExit =
     isBarStable
     and isLongTradeActive
     and (
        isMacroHostile
        or high > takeProfit
        or not isInSession
     )

isShortExit =
     isBarStable
     and isShortTradeActive
     and (
        isMacroSupportive
        or takeProfit > low
        or not isInSession
     )

if isLongExit
    isLongTradeActive := false
    exitPrice := close
    profit := exitPrice - entryPrice

if isShortExit
    isShortTradeActive := false
    exitPrice := close
    profit := entryPrice - exitPrice

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// STRATEGY
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

if isGC and isLongEntry
    strategy.entry("long", strategy.long)
if isGC and isShortEntry
    strategy.entry("short", strategy.short)
if isGC and isLongExit
    strategy.close("long")
if isGC and isShortExit
    strategy.close("short")

// PLOT
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// colors
ZN_color = color.purple
E6_color = color.teal
GC_color = color.yellow
long_color = color.blue
short_color = color.red
win_color = color.green
loss_color = color.red
session_color = color.gray
line_color = color.white

// transparency
bar_transparency = 50
signal_tranparency = 0
line_transparency = 80
bg_macro_transparency = 90
bg_session_transparency = 50

line_width = 2

// asset name (top right)
assetName =
     isZN ? "10Y Treasury (ZN)" :
     isE6 ? "Euro FX (6E)" :
     isGC ? "Gold (GC)" :
     "Untagged signal\n" + syminfo.description + " (" + syminfo.ticker + ")"

assetNameColor =
     isZN ? color.green :
     isE6 ? color.purple :
     isGC ? color.yellow :
     color.red

var table assetTable = table.new(position.top_right, 1, 1)

if barstate.islast
    table.cell(assetTable, 0, 0, assetName,
         text_color = assetNameColor,
         text_size = size.normal,
         text_halign = text.align_right,
         bgcolor = na)

/////////////////////////////////////////////////

// bar color
barColor =
     isZN and isZNsupportive ? color.new(long_color, bar_transparency) :
     isZN and isZNhostile ? color.new(short_color, bar_transparency) :
     isZN ? color.new(ZN_color, bar_transparency) :
     isE6 and isE6supportive ? color.new(long_color, bar_transparency) :
     isE6 and isE6hostile ? color.new(short_color, bar_transparency) :
     isE6 ? color.new(E6_color, bar_transparency) :
     not isInSession ? color.new(session_color, bar_transparency) :
     isGC and isGCsupportive ? color.new(long_color, bar_transparency) :
     isGC and isGChostile ? color.new(short_color, bar_transparency) :
     isGC ? color.new(GC_color, bar_transparency) : na
barcolor(barColor)

// background
usaOpeningTime = "0900-0901"
isUsaMarketOpening = not na(time(timeframe.period, usaOpeningTime, "America/New_York"))
bgcolor(
     isSessionClosing or isUsaMarketOpening ? color.new(session_color, bg_session_transparency) :
     isGC and isMacroSupportive ? color.new(long_color, bg_macro_transparency) :
     isGC and isMacroHostile ? color.new(short_color, bg_macro_transparency) : na
)

// entry
plot(
     isGC and isLongEntry ? entryPrice : na,
     style = plot.style_circles,
     color = color.new(long_color, signal_tranparency),
     linewidth = 5)
plot(
     isGC and isShortEntry ? entryPrice : na,
     style = plot.style_circles,
     color = color.new(short_color, signal_tranparency),
     linewidth = 5)

// exit
exit_color =
     profit >= 0 ? color.new(win_color, signal_tranparency) :
     color.new(loss_color, signal_tranparency)
plotshape(
     isGC and (isLongExit or isShortExit) ? exitPrice : na,
     title = "Long Exit",
     style = shape.xcross,
     location = location.absolute,
     color = exit_color,
     size = size.tiny)

// lines
plot(isZN ? znVwap : na, color = color.new(session_color, line_transparency), linewidth = line_width)
plot(isE6 ? e6Vwap : na , color = color.new(session_color, line_transparency), linewidth = line_width)
plot(isGC ? gcVwap : na, color = color.new(session_color, line_transparency), linewidth = line_width)
// plot(isGC ? gcAvg : na , color = color.new(GC_color, line_transparency), linewidth = line_width)

// ALERT
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// Event • Direction/State • Context • Value

var string alertMessage = na
var int lastMacroAlertBar = 0
var int lastMacroAlertDirection = 0 // -1 hostile, 0 neutral, 1 supportive

// reset alert container
alertMessage := na

// cooldown since last macro alert
MACRO_COOLDOWN_BARS = 15
barsSinceMacro = bar_index - lastMacroAlertBar
isMacroCooldownPassed = barsSinceMacro >= MACRO_COOLDOWN_BARS

// magnitude
formattedPrice = str.tostring(math.round_to_mintick(open), "#.00")

gcPrevClose = request.security(GC_SYMBOL, "D", close[1])
gcSessionPercent = (open - gcPrevClose) / gcPrevClose * 100.0

formattedPercent =
     math.abs(gcSessionPercent) < 0.005 ? "0%" :
     gcSessionPercent > 0 ? "+" + str.tostring(math.abs(gcSessionPercent), "0.00") + "%" :
     "-" + str.tostring(math.abs(gcSessionPercent), "0.00") + "%"

formattedMagnitude = formattedPrice + " • " + formattedPercent

// calculate p&l in ticks (protect user financial implications spoken aloud)
tickSize = syminfo.mintick
longTicks = math.round((open - entryPrice) / tickSize)
shortTicks = math.round((entryPrice - open) / tickSize)

// macro supportive
triggerMacroSupportive =
     isGC
     and isMacroSupportive
     and isMacroSupportive[1]
     and isMacroCooldownPassed
     and lastMacroAlertDirection != 1

if triggerMacroSupportive
    if na(alertMessage)
        alertMessage :=
             "Macro • Supportive alignment • " +
             formattedMagnitude

        lastMacroAlertBar := bar_index
        lastMacroAlertDirection := 1

// macro hostile
triggerMacroHostile =
     isGC
     and isMacroHostile
     and isMacroHostile[1]
     and isMacroCooldownPassed
     and lastMacroAlertDirection != -1

if triggerMacroHostile
    if na(alertMessage)
        alertMessage :=
             "Macro • Hostile alignment • " +
             formattedMagnitude

        lastMacroAlertBar := bar_index
        lastMacroAlertDirection := -1

// entry
if isGC and isLongEntry
    if na(alertMessage)
        alertMessage :=
             "Alignment • Bullish confirmation • " +
             formattedMagnitude

if isGC and isShortEntry
    if na(alertMessage)
        alertMessage :=
             "Alignment • Bearish confirmation • " +
             formattedMagnitude

// exit long
if isGC and isLongExit
    if na(alertMessage)
        isYieldRising = isZNhostile
        isDollarStronger = isE6hostile

        exitReason =
             isYieldRising and not isDollarStronger ? "Yields rising" :
             isDollarStronger and not isYieldRising ? "Dollar strengthening" :
             "Macro alignment lost"

        alertMessage :=
             "Weakness • " +
             exitReason + " • " +
             formattedMagnitude

// exit short
if isGC and isShortExit
    if na(alertMessage)
        isTreasuriesStronger = isZNsupportive
        isDollarWeaker = isE6supportive

        exitReason =
             isTreasuriesStronger and not isDollarWeaker ? "Treasuries strengthening" :
             isDollarWeaker and not isTreasuriesStronger ? "Dollar weakening" :
             "Macro alignment lost"

        alertMessage :=
             "Weakness • " +
             exitReason + " • " +
             formattedMagnitude

// OPEN GAP
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

OPEN_GAP_MAGNITUDE_POINTS = 18.0

marketOpeningTime = "1800-1801"
isMarketOpening = not na(time(timeframe.period, marketOpeningTime, "America/New_York"))

isOpenGapUp =
     isMarketOpening
     and high - close[1] > OPEN_GAP_MAGNITUDE_POINTS

isOpenGapDown =
     isMarketOpening
     and close[1] - low > OPEN_GAP_MAGNITUDE_POINTS

isOpenGap =
     isOpenGapUp
     or isOpenGapDown

formattedGapPoints = str.tostring(math.round(math.abs(open - close[1]))) + " points"

// open gap fires on bar close to capture full magnitude, special case
if isGC and isOpenGap and barstate.isconfirmed
    if na(alertMessage)
        alertMessage :=
             "Gap • " +
             (isOpenGapUp ? "Bullish market open imbalance • " : "Bearish market open imbalance • ") +
             formattedGapPoints

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// alert
if not na(alertMessage)
    alert(alertMessage, alert.freq_once_per_bar)